/*ĐỀ TÀI: QUẢN LÝ BÃI GỬI XE THÔNG MINH
	- QUẸT THẺ
	- CHECK SÔ TIỀN DƯ TRONG TÀI KHOẢN
	- CHECK MẤT XE BẰNG MÃ THẺ
	- TẠO ĐĂNG KÍ KHÁCH HÀNG MỚI
	- THỨ 5 TUẦN SAU THI
*/

CREATE DATABASE QL_BAIXE_THONGMINH
GO
USE QL_BAIXE_THONGMINH
GO

CREATE TABLE NHANVIEN(
	ID VARCHAR(6) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	NSINH DATE, 
	DIACHI NVARCHAR(100),
	SDT VARCHAR(10),
	SO_CCCD VARCHAR(12),
	AVT NVARCHAR(400),
	TRANGTHAI BIT DEFAULT 1
)
GO
CREATE TABLE NGUOIDUNG
(
	ID VARCHAR(6) PRIMARY KEY,
	MATKHAU VARCHAR(50) DEFAULT N'1111',
	TRANGTHAI BIT DEFAULT 0, -- 1 KICH HOAT 0 KHÔNG,
	LOAI BIT DEFAULT 0
)
GO

CREATE TABLE KHACHHANG(
	ID VARCHAR(6) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	SDT VARCHAR(10),
	DIACHI NVARCHAR(100),
	SO_CCCD VARCHAR(12),
	AVT VARCHAR(400),
	NGAY_DK DATE,
	TRANGTHAI BIT --1 KICH HOAT, 0 KHÔNG
)
GO

drop table VE_NGAY
CREATE TABLE VE_NGAY(
	ID VARCHAR(6) PRIMARY KEY,
	BIENSO VARCHAR(10),
	TRANGTHAI BIT DEFAULT 0
)
GO

create TABLE VE_THANG(
	ID VARCHAR(6) PRIMARY KEY,
	SODU INT DEFAULT 0,
	KHACHHANG_ID VARCHAR(6) REFERENCES DBO.KHACHHANG(ID),
	MODE_XE NVARCHAR(50),
	BIENSO VARCHAR(10),
	TRANGTHAI BIT DEFAULT 0 -- 1 KÍCH HOẠT, 0 - KHÔNG 
)
GO
SELECT * FROM VE_THANG

drop table giaodich
CREATE TABLE GIAODICH(
	ID VARCHAR(6) PRIMARY KEY,
	CHECKIN DATETIME,
	CHECKOUT DATETIME,
	VE_ID VARCHAR(6) REFERENCES DBO.VE_THANG(ID),
	USER_ID VARCHAR(6) REFERENCES DBO.NGUOIDUNG(ID),
	TRANGTHAI BIT 
)
ALTER TABLE GIAODICH ADD TIENGUI INT
-------------

CREATE FUNCTION F_AUTO_ID(@LASTID VARCHAR(6),@TIENTO VARCHAR(6),@SIZE int) 
RETURNS VARCHAR(6)
AS
BEGIN
	IF(@LASTID = '')
	-- Hàm replicate ('abc',x): nhân chuỗi 'abc' lên x lần  
	SET @LASTID = @TIENTO + REPLICATE (0,@SIZE - LEN(@TIENTO))
	DECLARE @NUM_NEXTID INT, @NEXTID VARCHAR(6)

	SET @LASTID = LTRIM(RTRIM(@LASTID))

	-- number next id = thay thế phần TIỀN TỐ trong lastid bằng null (tách lấy phần số)
	SET @NUM_NEXTID = replace(@LASTID,@TIENTO,'') + 1

	-- bo di so luong ky tu tien to
	SET @SIZE = @SIZE - len(@TIENTO)

	-- replicate số lượng số 0 REPLICATE(0,3) => 000
	SET @NEXTID = @TIENTO + REPLICATE (0,@SIZE - LEN(@TIENTO))
	SET @NEXTID = @TIENTO + RIGHT(REPLICATE(0, @SIZE) + CONVERT (VARCHAR(MAX), @NUM_NEXTID), @SIZE)
	RETURN @NEXTID
END;
GO
-----TRIGGER TỰ THÊM ID
CREATE TRIGGER TG_AUTOID_KHACHHANG ON KHACHHANG
FOR INSERT
AS
BEGIN
	DECLARE @LASTID VARCHAR(6)
	SET @LASTID = (SELECT TOP 1 ID FROM KHACHHANG ORDER BY ID DESC)
	UPDATE KHACHHANG SET ID = DBO.F_AUTO_ID(@LASTID,'KH',6) WHERE ID = ''
END
GO
DROP TRIGGER TG_CHECK_CCCD
--- TRIGGER CHECK SỐ CCCD CÓ TRÙNG NHAU KHÔNG

--ALTER TRIGGER TG_CHECK_CCCD ON KHACHHANG
--FOR INSERT, UPDATE
--AS
--BEGIN
--	DECLARE @NEW_CCCD VARCHAR(12) = (SELECT SO_CCCD FROM inserted)
--	IF (SELECT COUNT(*) FROM KHACHHANG WHERE SO_CCCD = @NEW_CCCD GROUP BY SO_CCCD) >0 
--	BEGIN
--		ROLLBACK TRAN
--	END
--END
-------
DROP TRIGGER TG_CHECK_CCCD

CREATE TRIGGER TG_CHECK_CCCD ON KHACHHANG
INSTEAD OF INSERT, UPDATE
AS
BEGIN
	DECLARE @NEW_CCCD VARCHAR(12) = (SELECT SO_CCCD FROM inserted)
	IF (SELECT COUNT(*) FROM KHACHHANG WHERE SO_CCCD = @NEW_CCCD GROUP BY SO_CCCD) >0 
	BEGIN
	PRINT N'CCCD TRÙNG'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		DECLARE @HOTEN NVARCHAR(50),
		@SDT VARCHAR(10),
		@DIACHI NVARCHAR(100),
		@SO_CCCD VARCHAR(12),
		@AVT NVARCHAR(400),
		@NGAYDK DATE,
		@TRANGTHAI BIT
		SELECT @HOTEN = HOTEN, @SDT = SDT, @DIACHI = DIACHI, @SO_CCCD = SO_CCCD, @AVT = AVT, @NGAYDK = NGAY_DK, @TRANGTHAI = TRANGTHAI FROM inserted
		INSERT DBO.KHACHHANG(ID, HOTEN, SDT, DIACHI, SO_CCCD, AVT, NGAY_DK, TRANGTHAI) VALUES('',@HOTEN, @SDT, @DIACHI, @SO_CCCD, @AVT, @NGAYDK, @TRANGTHAI)
	END
END

----
DROP TRIGGER TG_CHECK_BIENSO
ALTER TRIGGER TG_CHECK_BIENSO ON VE_THANG
INSTEAD OF UPDATE
AS
BEGIN
	DECLARE @NEW_BIENSO VARCHAR(10) = (SELECT BIENSO FROM inserted)
	IF (SELECT COUNT(*) FROM VE_THANG WHERE BIENSO = @NEW_BIENSO GROUP BY BIENSO) >0
	BEGIN
	PRINT N'BIỂN SỐ TRÙNG'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		DECLARE	@ID_VE VARCHAR(6),
		@KHACH_ID VARCHAR(6),
		@SODU INT,
		@MODE_XE NVARCHAR(50),
		@BIENSO VARCHAR(10)

		SELECT @ID_VE = ID, @KHACH_ID = KHACHHANG_ID, @SODU = SODU, @MODE_XE = MODE_XE, @BIENSO = BIENSO FROM inserted
		UPDATE DBO.VE_THANG SET KHACHHANG_ID = @KHACH_ID, SODU = @SODU, MODE_XE = @MODE_XE, BIENSO = @BIENSO WHERE ID = @ID_VE
	END
END
--- 
CREATE TRIGGER TG_AUTOID_VETHANG ON VE_THANG
FOR INSERT
AS
BEGIN
	DECLARE @LASTID VARCHAR(6)
	SET @LASTID = (SELECT TOP 1 ID FROM VE_THANG ORDER BY ID DESC)
	UPDATE VE_THANG SET ID = DBO.F_AUTO_ID(@LASTID,'VT',6) WHERE ID = ''
END
GO
-------------------------
-- PROC THÊM KHÁCH HÀNG
CREATE PROC PR_DKKH_MOI(
	@HOTEN NVARCHAR(50),
	@SDT VARCHAR(10),
	@DIACHI NVARCHAR(100),
	@SO_CCCD VARCHAR(12),
	@AVT NVARCHAR(400),
	@ID_VE VARCHAR(6),
	@SODU INT,
	@MODE_XE NVARCHAR(50),
	@BIENSO VARCHAR(10)
)

AS
BEGIN
	BEGIN TRAN
		SAVE TRAN savetran1
			DECLARE @NGAY DATETIME = (SELECT GETDATE())
			INSERT DBO.KHACHHANG(ID,HOTEN, SDT, DIACHI,SO_CCCD, AVT, NGAY_DK, TRANGTHAI)
			VALUES('',@HOTEN,@SDT,@DIACHI,@SO_CCCD ,@AVT, @NGAY, 1)
		SAVE TRAN savetran2
			UPDATE DBO.VE_THANG 
			SET SODU = @SODU, MODE_XE = @MODE_XE, BIENSO = @BIENSO, KHACHHANG_ID = (SELECT TOP 1 ID FROM KHACHHANG ORDER BY ID DESC), TRANGTHAI = 1
			WHERE ID = @ID_VE
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRAN savetran1
				COMMIT TRAN
			END
		ELSE COMMIT TRAN
END
GO

--- PROC LẤY ID TỪ CCCD
ALTER PROC PR_GET_ID_KH(
	@CCCD VARCHAR(12)
)
AS
BEGIN
	SELECT ID FROM KHACHHANG WHERE SO_CCCD = @CCCD
END

----- PROC UPDATE KHÁCH HÀNG, VÉ THÁNG

ALTER PROC PR_EDIT_KH(
	@VE_ID VARCHAR(6),
	@HOTEN NVARCHAR(50),
	@SDT VARCHAR(10),
	@DIACHI NVARCHAR(100),
	@SO_CCCD VARCHAR(12),
	@AVT NVARCHAR(400),
	@SODU INT,
	@MODE_XE NVARCHAR(50),
	@BIENSO VARCHAR(10)
)
AS
BEGIN
	BEGIN TRAN
		SAVE TRAN ST1
			DECLARE @IDKH VARCHAR(6)
			SET @IDKH = 
			(SELECT KHACHHANG.ID FROM KHACHHANG JOIN VE_THANG ON VE_THANG.KHACHHANG_ID = KHACHHANG.ID
			WHERE VE_THANG.ID = @VE_ID)
		SAVE TRAN ST2
			UPDATE DBO.KHACHHANG 
			SET HOTEN = @HOTEN, SDT = @SDT, DIACHI = @DIACHI, SO_CCCD = @SO_CCCD, AVT = @AVT, TRANGTHAI = 1
			WHERE ID = @IDKH
		SAVE TRAN ST3
			UPDATE DBO.VE_THANG
			SET MODE_XE = @MODE_XE, SODU = @SODU, BIENSO = @BIENSO, TRANGTHAI = 1
			WHERE ID = @VE_ID
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRAN ST1
				COMMIT TRAN
			END
		ELSE COMMIT TRAN
END

--UPDATE DBO.KHACHHANG SET SO_CCCD = N'012345678999' WHERE ID = N'KH0004'

EXEC PR_EDIT_KH N'VT0001', N'VŨ NHỊ LỤC', N'0983123567', N'GIA BÌNH - BẮC NINH', N'32156789059', NULL, 100000, N'YAMAHA-SIRIUS-TRẮNG', N'99H5-00010'

--EXEC PR_EDIT_KH @VE_ID , @HOTEN , @SDT , @DIACHI , @SO_CCCD, @AVT , @SODU , @MODE_XE , @BIENSO

select * from khachhang
select * from VE_THANG

---- PROC XÓA KHÁCH HÀNG
alter PROC PR_DEL_KH(
	@ID VARCHAR(6)
)
AS
BEGIN
	BEGIN TRAN
		SAVE TRAN SAVETRAN1
			UPDATE DBO.KHACHHANG SET TRANGTHAI = 0 WHERE ID = @ID
		SAVE TRAN SAVETRAN2
			UPDATE DBO.VE_THANG SET TRANGTHAI = 0, SODU = 0, KHACHHANG_ID = null, MODE_XE =null, BIENSO = null WHERE KHACHHANG_ID = @ID
		IF @@ERROR <>0
			BEGIN
				ROLLBACK TRAN SAVERTRAN1
				COMMIT TRAN
			END
		ELSE
			COMMIT TRAN
END
--SELECT * FROM KHACHHANG

--EXEC PR_DEL_KH @ID

--EXEC PR_DSKH_VEDK

----- LẤY DS KHÁCH HÀNG, CÓ PHÂN TRANG
alter PROC PR_DSKH_VEDK_IN_PAGE(
	@PAGE INT,
	@PAGE_SIZE INT
)
AS
BEGIN	
	DECLARE @SELECT_ROW INT= @PAGE_SIZE * @PAGE
	DECLARE @EXCEPT_ROW INT= @PAGE_SIZE *(@PAGE -1)

	;WITH KH_VT AS 
	(SELECT KHACHHANG.HOTEN, VE_THANG.MODE_XE, VE_THANG.BIENSO, VE_THANG.SODU, KHACHHANG.NGAY_DK, KHACHHANG.SDT,KHACHHANG.SO_CCCD, KHACHHANG.DIACHI 
	FROM KHACHHANG JOIN VE_THANG
		ON KHACHHANG.ID = VE_THANG.KHACHHANG_ID
	WHERE KHACHHANG.TRANGTHAI = 1)

	 SELECT TOP(@SELECT_ROW) * FROM KH_VT
	 EXCEPT
	 SELECT TOP(@EXCEPT_ROW) * FROM KH_VT

END
GO
--exec PR_DSKH_VEDK_IN_PAGE 1, 2
----PROC ĐẾM TỔNG SỐ KHÁCH HÀNG THỎA MÃN ĐK
CREATE PROC PR_TONG_KH
AS
BEGIN
	SELECT COUNT(*) 
	FROM KHACHHANG JOIN VE_THANG
		ON KHACHHANG.ID = VE_THANG.KHACHHANG_ID
	WHERE KHACHHANG.TRANGTHAI = 1
END


-----LẤY DS KHÁCH HÀNG, KHÔNG PHÂN TRANG
ALTER PROC PR_DSKH_VEDK
AS
BEGIN
	SELECT KHACHHANG.HOTEN, VE_THANG.MODE_XE, VE_THANG.BIENSO, VE_THANG.SODU, KHACHHANG.NGAY_DK, KHACHHANG.SDT,KHACHHANG.SO_CCCD, KHACHHANG.DIACHI 
	FROM KHACHHANG JOIN VE_THANG
		ON KHACHHANG.ID = VE_THANG.KHACHHANG_ID
	WHERE KHACHHANG.TRANGTHAI = 1
END


--DECLARE @COUT INT = 0
--WHILE(@COUT <20)
--	BEGIN
--		 INSERT DBO.VE_THANG(ID,SODU) VALUES('',0)
--		 SET  @COUT= @COUT +1
--	END
EXEC PR_DKKH_MOI N'VŨ ĐỆ LỤC', N'09021623', N'BẮC KAN', N'196420001', NULL, N'VT0014', 100000, N'YAMAHA-SIRIUS-ĐEN', N'92B1-27235'

--SELECT * FROM VE_THANG
SELECT * FROM VE_THANG
