/*ĐỀ TÀI: QUẢN LÝ BÃI GỬI XE THÔNG MINH
	- QUẸT THẺ
	- CHECK SÔ TIỀN DƯ TRONG TÀI KHOẢN
	- CHECK MẤT XE BẰNG MÃ THẺ
	- TẠO ĐĂNG KÍ KHÁCH HÀNG MỚI
	- THỨ 5 TUẦN SAU THI
*/

CREATE DATABASE QL_BAIXE_THONGMINH
GO
USE QL_BAIXE_THONGMINH
GO

CREATE TABLE NHANVIEN(
	ID CHAR(6) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	NSINH DATE, 
	DIACHI NVARCHAR(100),
	SDT CHAR(10),
	SO_CCCD CHAR(12),
	AVT nvarchar(400),
	TRANGTHAI BIT DEFAULT 1
)
GO
CREATE TABLE NGUOIDUNG
(
	ID CHAR(6) PRIMARY KEY,
	MATKHAU VARCHAR(50) DEFAULT N'1111',
	TRANGTHAI BIT DEFAULT 0, -- 1 KICH HOAT 0 KHÔNG,
	LOAI BIT
)
GO

CREATE TABLE KHACHHANG(
	ID CHAR(6) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	SDT CHAR(10),
	DIACHI NVARCHAR(100),
	SO_CCCD CHAR(12),
	AVT nvarchar(400),
	NGAY_DK DATE,
	TRANGTHAI BIT --1 KICH HOAT, 0 KHÔNG
)
GO

CREATE TABLE VE_NGAY(
	ID CHAR(6) PRIMARY KEY,
	BIENSO CHAR(10),
	TRANGTHAI BIT DEFAULT 0
)
GO

create TABLE VE_THANG(
	ID CHAR(6) PRIMARY KEY,
	SODU INT DEFAULT 0,
	KHACHHANG_ID CHAR(6) REFERENCES DBO.KHACHHANG(ID),
	MODE_XE NVARCHAR(50),
	BIENSO CHAR(10),
	TRANGTHAI BIT DEFAULT 0 -- 1 KÍCH HOẠT, 0 - KHÔNG 
)
GO

CREATE TABLE GIAODICH(
	ID CHAR(6) PRIMARY KEY,
	CHECKIN DATETIME,
	CHECKOUT DATETIME,
	VE_ID CHAR(6) REFERENCES DBO.VE_NGAY(ID),
	USER_ID CHAR(6) REFERENCES DBO.NGUOIDUNG(ID),
	TRANGTHAI BIT 
)

ALTER TABLE GIAODICH ADD FOREIGN KEY (VE_ID) REFERENCES VE_THANG(ID)
GO
-------------

CREATE FUNCTION F_AUTO_ID(@LASTID CHAR(6),@TIENTO CHAR(6),@SIZE int) 
RETURNS VARCHAR(10)
AS
BEGIN
	IF(@LASTID = '')
	-- Hàm replicate ('abc',x): nhân chuỗi 'abc' lên x lần  
	SET @LASTID = @TIENTO + REPLICATE (0,@SIZE - LEN(@TIENTO))
	DECLARE @NUM_NEXTID INT, @NEXTID CHAR(6)

	SET @LASTID = LTRIM(RTRIM(@LASTID))

	-- number next id = thay thế phần TIỀN TỐ trong lastid bằng null (tách lấy phần số)
	SET @NUM_NEXTID = replace(@LASTID,@TIENTO,'') + 1

	-- bo di so luong ky tu tien to
	SET @SIZE = @SIZE - len(@TIENTO)

	-- replicate số lượng số 0 REPLICATE(0,3) => 000
	SET @NEXTID = @TIENTO + REPLICATE (0,@SIZE - LEN(@TIENTO))
	SET @NEXTID = @TIENTO + RIGHT(REPLICATE(0, @SIZE) + CONVERT (VARCHAR(MAX), @NUM_NEXTID), @SIZE)
	RETURN @NEXTID
END;
GO


CREATE TRIGGER TG_AUTOID_KHACHHANG ON KHACHHANG
FOR INSERT
AS
BEGIN
	DECLARE @LASTID CHAR(6)
	SET @LASTID = (SELECT TOP 1 ID FROM KHACHHANG ORDER BY ID DESC)
	UPDATE KHACHHANG SET ID = DBO.F_AUTO_ID(@LASTID,'KH',6) WHERE ID = ''
END

-------------------------
-- PROC THÊM KHÁCH HÀNG
EXEC PR_DKKH_MOI N'VŨ HẢI', N'0987123567', N'GIA LỘC - HẢI DƯƠNG', N'123456789056', NULL, N'VT0003', 200000, N'YAMAHA-SIRIUS-XANH ĐEN', N'35H1-11111'

DELETE KHACHHANG
SELECT * FROM KHACHHANG
INSERT DBO.KHACHHANG(ID, HOTEN) VALUES('', N'HIHI')
DELETE VE_THANG
SELECT * FROM VE_THANG

CREATE PROC PR_DKKH_MOI(
	@HOTEN NVARCHAR(50),
	@SDT CHAR(10),
	@DIACHI NVARCHAR(100),
	@SO_CCCD CHAR(12),
	@AVT NVARCHAR(400),
	@ID_VE CHAR(6),
	@SODU INT,
	@MODE_XE NVARCHAR(50),
	@BIENSO CHAR(10)
)
AS
BEGIN
	BEGIN TRAN
		SAVE TRAN savetran1
			DECLARE @NGAY DATETIME = (SELECT GETDATE())
			INSERT DBO.KHACHHANG(ID,HOTEN, SDT, DIACHI,SO_CCCD, AVT, NGAY_DK, TRANGTHAI)
			VALUES('',@HOTEN,@SDT,@DIACHI,@SO_CCCD ,@AVT, @NGAY, 1)
		SAVE TRAN savetran2
			UPDATE DBO.VE_THANG 
			SET SODU = @SODU, MODE_XE = @MODE_XE, BIENSO = @BIENSO, KHACHHANG_ID = (SELECT TOP 1 ID FROM KHACHHANG ORDER BY ID DESC), TRANGTHAI = 1
			WHERE ID = @ID_VE
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRAN savetran1
				COMMIT TRAN
			END
		ELSE COMMIT TRAN
END
GO